version: '3'

volumes:
  mariadb-data:

services:

  mariadb:
    image: dsuite/mariadb:10.5
    restart: always
    environment:
      - DEBUG_LEVEL=DEBUG
      - MYSQL_ROOT_PASSWORD=MyRootPassword
      - MYSQL_DATABASE=my_database
      - MYSQL_USER=MyUser
      - MYSQL_PASSWORD=MyDbPassword
    volumes:
     - ./config:/mariadb/config
     - mariadb-data:/mariadb/data
     - ./tmp/db_backup:/mariadb/backup
     - ./tmp/log:/var/log

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mariadb
