version: '3.8'

services:

  mariadb:
    image: dsuite/mariadb
    command: --innodb_buffer_pool_size=1024M --innodb_read_io_threads=4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPassord
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
     - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mariadb-cron-backup:
    image: dsuite/mariadb
    restart: always
    entrypoint: /backup_cron.sh
    environment:
      BACKUP_MYSQL_HOST: mariadb
      BACKUP_MYSQL_PORT: 3306
      BACKUP_CRON_TIME: "0 3 * * *"
      MYSQL_ROOT_PASSWORD: MyStrongPassord
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    depends_on:
      - mariadb
    volumes:
     - ./backup/:/backup
     - ./log/:/var/log/mysql

volumes:
  mariadb_data:
