#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/persist-env.sh

[ -n "$(env_get "MARIADB_MAJOR")" ] && env_set "MARIADB_MAJOR" "$(env_get "MARIADB_MAJOR")"
[ -n "$(env_get "MARIADB_VERSION")" ] && env_set "MARIADB_VERSION" "$(env_get "MARIADB_VERSION")"

# Environment variables
[ -n "$(env_get "MYSQL_ALLOW_EMPTY_PASSWORD")" ] && env_set "MYSQL_ALLOW_EMPTY_PASSWORD" "$(env_get "MYSQL_ALLOW_EMPTY_PASSWORD")"
[ -n "$(env_get "MYSQL_BACKUP_COUNT")" ] && env_set "MYSQL_BACKUP_COUNT" "$(env_get "MYSQL_BACKUP_COUNT")"
[ -n "$(env_get "MYSQL_BACKUP_DIR")" ] && env_set "MYSQL_BACKUP_DIR" "$(env_get "MYSQL_BACKUP_DIR")"
[ -n "$(env_get "MYSQL_DATA_DIR")" ] && env_set "MYSQL_DATA_DIR" "$(env_get "MYSQL_DATA_DIR")"
[ -n "$(env_get "MYSQL_DATABASE")" ] && env_set "MYSQL_DATABASE" "$(env_get "MYSQL_DATABASE")"
[ -n "$(env_get "MYSQL_INSTALL_PARAMS")" ] && env_set "MYSQL_INSTALL_PARAMS" "$(env_get "MYSQL_INSTALL_PARAMS")"
[ -n "$(env_get "MYSQL_PASSWORD")" ] && env_set "MYSQL_PASSWORD" "$(env_get "MYSQL_PASSWORD")"
[ -n "$(env_get "MYSQL_RANDOM_ROOT_PASSWORD")" ] && env_set "MYSQL_RANDOM_ROOT_PASSWORD" "$(env_get "MYSQL_RANDOM_ROOT_PASSWORD")"
[ -n "$(env_get "MYSQL_ROOT_PASSWORD")" ] && env_set "MYSQL_ROOT_PASSWORD" "$(env_get "MYSQL_ROOT_PASSWORD")"
[ -n "$(env_get "MYSQL_STARTCMD")" ] && env_set "MYSQL_STARTCMD" "$(env_get "MYSQL_STARTCMD")"
[ -n "$(env_get "MYSQL_STARTPARAMS")" ] && env_set "MYSQL_STARTPARAMS" "$(env_get "MYSQL_STARTPARAMS")"
[ -n "$(env_get "MYSQL_USER")" ] && env_set "MYSQL_USER" "$(env_get "MYSQL_USER")"
[ -n "$(env_get "TIMEZONE")" ] && env_set "TIMEZONE" "$(env_get "TIMEZONE")"

# Config environment variables
[ -n "$(env_get "MYSQL_BIND_ADRESS")" ] && env_set "MYSQL_BIND_ADRESS" "$(env_get "MYSQL_BIND_ADRESS")"
[ -n "$(env_get "MYSQL_BINLOG_FORMAT")" ] && env_set "MYSQL_BINLOG_FORMAT" "$(env_get "MYSQL_BINLOG_FORMAT")"
[ -n "$(env_get "MYSQL_CHARACTER_SET_SERVER")" ] && env_set "MYSQL_CHARACTER_SET_SERVER" "$(env_get "MYSQL_CHARACTER_SET_SERVER")"
[ -n "$(env_get "MYSQL_CLIENT_DEFAULT_CHARACTER_SET")" ] && env_set "MYSQL_CLIENT_DEFAULT_CHARACTER_SET" "$(env_get "MYSQL_CLIENT_DEFAULT_CHARACTER_SET")"
[ -n "$(env_get "MYSQL_COLLATION_SERVER")" ] && env_set "MYSQL_COLLATION_SERVER" "$(env_get "MYSQL_COLLATION_SERVER")"
[ -n "$(env_get "MYSQL_DUMP_MAX_ALLOWED_PACKET")" ] && env_set "MYSQL_DUMP_MAX_ALLOWED_PACKET" "$(env_get "MYSQL_DUMP_MAX_ALLOWED_PACKET")"
[ -n "$(env_get "MYSQL_GENERAL_LOG")" ] && env_set "MYSQL_GENERAL_LOG" "$(env_get "MYSQL_GENERAL_LOG")"
[ -n "$(env_get "MYSQL_INNODB_BUFFER_POOL_SIZE")" ] && env_set "MYSQL_INNODB_BUFFER_POOL_SIZE" "$(env_get "MYSQL_INNODB_BUFFER_POOL_SIZE")"
[ -n "$(env_get "MYSQL_INNODB_DATA_FILE_PATH")" ] && env_set "MYSQL_INNODB_DATA_FILE_PATH" "$(env_get "MYSQL_INNODB_DATA_FILE_PATH")"
[ -n "$(env_get "MYSQL_INNODB_DEFAULT_ROW_FORMAT")" ] && env_set "MYSQL_INNODB_DEFAULT_ROW_FORMAT" "$(env_get "MYSQL_INNODB_DEFAULT_ROW_FORMAT")"
[ -n "$(env_get "MYSQL_INNODB_EMPTY_FREE_LIST_ALGORITHM")" ] && env_set "MYSQL_INNODB_EMPTY_FREE_LIST_ALGORITHM" "$(env_get "MYSQL_INNODB_EMPTY_FREE_LIST_ALGORITHM")"
[ -n "$(env_get "MYSQL_INNODB_FILE_FORMAT")" ] && env_set "MYSQL_INNODB_FILE_FORMAT" "$(env_get "MYSQL_INNODB_FILE_FORMAT")"
[ -n "$(env_get "MYSQL_INNODB_FILE_PER_TABLE")" ] && env_set "MYSQL_INNODB_FILE_PER_TABLE" "$(env_get "MYSQL_INNODB_FILE_PER_TABLE")"
[ -n "$(env_get "MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT")" ] && env_set "MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT" "$(env_get "MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT")"
[ -n "$(env_get "MYSQL_INNODB_LARGE_PREFIX")" ] && env_set "MYSQL_INNODB_LARGE_PREFIX" "$(env_get "MYSQL_INNODB_LARGE_PREFIX")"
[ -n "$(env_get "MYSQL_INNODB_LOCK_WAIT_TIMEOUT")" ] && env_set "MYSQL_INNODB_LOCK_WAIT_TIMEOUT" "$(env_get "MYSQL_INNODB_LOCK_WAIT_TIMEOUT")"
[ -n "$(env_get "MYSQL_INNODB_LOG_BUFFER_SIZE")" ] && env_set "MYSQL_INNODB_LOG_BUFFER_SIZE" "$(env_get "MYSQL_INNODB_LOG_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_INNODB_LOG_FILE_SIZE")" ] && env_set "MYSQL_INNODB_LOG_FILE_SIZE" "$(env_get "MYSQL_INNODB_LOG_FILE_SIZE")"
[ -n "$(env_get "MYSQL_INNODB_USE_NATIVE_AIO")" ] && env_set "MYSQL_INNODB_USE_NATIVE_AIO" "$(env_get "MYSQL_INNODB_USE_NATIVE_AIO")"
[ -n "$(env_get "MYSQL_KEY_BUFFER_SIZE")" ] && env_set "MYSQL_KEY_BUFFER_SIZE" "$(env_get "MYSQL_KEY_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_LOG_BIN")" ] && env_set "MYSQL_LOG_BIN" "$(env_get "MYSQL_LOG_BIN")"
[ -n "$(env_get "MYSQL_LOG_DIR")" ] && env_set "MYSQL_LOG_DIR" "$(env_get "MYSQL_LOG_DIR")"
[ -n "$(env_get "MYSQL_MAX_ALLOWED_PACKET")" ] && env_set "MYSQL_MAX_ALLOWED_PACKET" "$(env_get "MYSQL_MAX_ALLOWED_PACKET")"
[ -n "$(env_get "MYSQL_MYISAM_SORT_BUFFER_SIZE")" ] && env_set "MYSQL_MYISAM_SORT_BUFFER_SIZE" "$(env_get "MYSQL_MYISAM_SORT_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_MYISAMCHK_KEY_BUFFER_SIZE")" ] && env_set "MYSQL_MYISAMCHK_KEY_BUFFER_SIZE" "$(env_get "MYSQL_MYISAMCHK_KEY_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_MYISAMCHK_READ_BUFFER")" ] && env_set "MYSQL_MYISAMCHK_READ_BUFFER" "$(env_get "MYSQL_MYISAMCHK_READ_BUFFER")"
[ -n "$(env_get "MYSQL_MYISAMCHK_SORT_BUFFER_SIZE")" ] && env_set "MYSQL_MYISAMCHK_SORT_BUFFER_SIZE" "$(env_get "MYSQL_MYISAMCHK_SORT_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_MYISAMCHK_WRITE_BUFFER")" ] && env_set "MYSQL_MYISAMCHK_WRITE_BUFFER" "$(env_get "MYSQL_MYISAMCHK_WRITE_BUFFER")"
[ -n "$(env_get "MYSQL_NET_BUFFER_LENGTH")" ] && env_set "MYSQL_NET_BUFFER_LENGTH" "$(env_get "MYSQL_NET_BUFFER_LENGTH")"
[ -n "$(env_get "MYSQL_OPTIMIZER_PRUNE_LEVEL")" ] && env_set "MYSQL_OPTIMIZER_PRUNE_LEVEL" "$(env_get "MYSQL_OPTIMIZER_PRUNE_LEVEL")"
[ -n "$(env_get "MYSQL_OPTIMIZER_SEARCH_DEPTH")" ] && env_set "MYSQL_OPTIMIZER_SEARCH_DEPTH" "$(env_get "MYSQL_OPTIMIZER_SEARCH_DEPTH")"
[ -n "$(env_get "MYSQL_READ_BUFFER_SIZE")" ] && env_set "MYSQL_READ_BUFFER_SIZE" "$(env_get "MYSQL_READ_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_READ_RND_BUFFER_SIZE")" ] && env_set "MYSQL_READ_RND_BUFFER_SIZE" "$(env_get "MYSQL_READ_RND_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_SERVER_ID")" ] && env_set "MYSQL_SERVER_ID" "$(env_get "MYSQL_SERVER_ID")"
[ -n "$(env_get "MYSQL_SLOW_QUERY_LOG")" ] && env_set "MYSQL_SLOW_QUERY_LOG" "$(env_get "MYSQL_SLOW_QUERY_LOG")"
[ -n "$(env_get "MYSQL_SORT_BUFFER_SIZE")" ] && env_set "MYSQL_SORT_BUFFER_SIZE" "$(env_get "MYSQL_SORT_BUFFER_SIZE")"
[ -n "$(env_get "MYSQL_TABLE_OPEN_CACHE")" ] && env_set "MYSQL_TABLE_OPEN_CACHE" "$(env_get "MYSQL_TABLE_OPEN_CACHE")"
[ -n "$(env_get "MYSQL_TRANSACTION_ISOLATION")" ] && env_set "MYSQL_TRANSACTION_ISOLATION" "$(env_get "MYSQL_TRANSACTION_ISOLATION")"
