#!/usr/bin/env bash

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

WARNING "[MARIADB] -- Ending Service mariadb with parameters ${@}"

# Tell runit to stop runit:
[ "$1" = 1 ] && runit stop &
