#!/usr/bin/env bash

# set -e : Exit the script if any statement returns a non-true return value.
# set -u : Exit the script when using uninitialised variable.
set -eu

# Add libraries
source /usr/local/lib/bash-logger.sh
source /usr/local/lib/persist-env.sh

# Redirect STDERR to STDOUT
exec 2>&1

# Default values
export MYSQL_DATA_DIR=${MYSQL_DATA_DIR:='/mysql/db/'}
export MYSQL_INSTALL_PARAMS=${MYSQL_INSTALL_PARAMS:=''}
export MYSQL_STARTCMD=${MYSQL_STARTCMD:='/usr/bin/mysqld'}
export MYSQL_STARTPARAMS=${MYSQL_STARTPARAMS:='--skip-host-cache --skip-name-resolve --debug-gdb'} #'--skip-networking --skip-name-resolve --debug-gdb'}
export MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:=''}
export MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD:=false}
export MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD:=false}
export MYSQL_DATABASE=${MYSQL_DATABASE:=''}
export MYSQL_USER=${MYSQL_USER:=''}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:=''}


# If the MYSQL_DATA_DIR doesn't exist, this mean
# that we perform the first install.
if [ -z "$(ls -A $MYSQL_DATA_DIR)" ]; then

    # First, check for root password
    if [ -z "$MYSQL_ROOT_PASSWORD" ] && [ "$MYSQL_RANDOM_ROOT_PASSWORD" = 'false' ] && [ "$MYSQL_ALLOW_EMPTY_PASSWORD" = 'false' ]; then
        WARNING ''
        WARNING ''
        WARNING 'Error: database is uninitialized and password option is not specified'
        WARNING 'You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_RANDOM_ROOT_PASSWORD or MYSQL_ALLOW_EMPTY_PASSWORD'
        WARNING ''
        exit 1
    fi

    NOTICE ''
    NOTICE "An empty or uninitialized MariaDB volume is detected in $MYSQL_DATA_DIR"
    NOTICE ''
    NOTICE 'Installing MariaDB ...'
    NOTICE ''

    # Create the MYSQL_DATA_DIR and give full access to mysql user.
    mkdir -p "$MYSQL_DATA_DIR"
    chown -R mysql:mysql "$MYSQL_DATA_DIR"

    # By default, use the root password defined by the user
    # or use a random password if MYSQL_RANDOM_ROOT_PASSWORD is true
    # or use an empty password if MYSQL_ALLOW_EMPTY_PASSWORD is true
    if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
        # random password
        if [ "$MYSQL_RANDOM_ROOT_PASSWORD" = 'true' ]; then
            MYSQL_ROOT_PASSWORD="$(date +%s | sha256sum | md5sum | base64 | head -c 16)"
            WARNING "GENERATED ROOT PASSWORD: $MYSQL_ROOT_PASSWORD"
        # Empty password
        elif [ "$MYSQL_ALLOW_EMPTY_PASSWORD" = 'true' ]; then
            MYSQL_ROOT_PASSWORD="''"
        fi
    fi

    # It's time to initialize the database
    NOTICE ''
    NOTICE 'Initializing database ...'
    NOTICE '  mysql_install_db'
    NOTICE '    --user=mysql'
    NOTICE '    --basedir=/usr'
    NOTICE '    --datadir='"$MYSQL_DATA_DIR"
    NOTICE '    --rpm'
    NOTICE '    --cross-bootstrap'
    if [ -n "$MYSQL_INSTALL_PARAMS" ] ; then NOTICE '    '"$MYSQL_INSTALL_PARAMS"; fi
    NOTICE '    --defaults-file=/mysql/conf/my.cnf'
    NOTICE ''
    mysql_install_db --user=mysql --basedir=/usr --datadir="$MYSQL_DATA_DIR" --rpm --cross-bootstrap "$MYSQL_INSTALL_PARAMS" --defaults-file=/mysql/conf/my.cnf
    NOTICE ''
    NOTICE 'Database initialized'
    NOTICE ''

    # Init file used at startup
    INIT_FILE="/tmp/mariadb-boot.sql"

    # Create root user
    echo "
    USE mysql;
    FLUSH PRIVILEGES;
    GRANT ALL ON *.* TO 'root'@'%' identified by '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;
    GRANT ALL ON *.* TO 'root'@'localhost' identified by '$MYSQL_ROOT_PASSWORD' WITH GRANT OPTION;
    SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${MYSQL_ROOT_PASSWORD}');
    DROP DATABASE IF EXISTS test;
    FLUSH PRIVILEGES;
    " >| ${INIT_FILE}

    # Create database
    if [ -n "${MYSQL_USER}" ] && [ -n "${MYSQL_DATABASE}" ]; then
        NOTICE ''
        NOTICE "Creating database ${MYSQL_DATABASE} ..."
        echo "
        CREATE DATABASE IF NOT EXISTS \`${MYSQL_DATABASE}\`;
        GRANT ALL PRIVILEGES ON \`${MYSQL_DATABASE}\`.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
        FLUSH PRIVILEGES;
        " >> ${INIT_FILE}
    fi

    # Create user database
    if [ -n "${MYSQL_USER}" ] && [ -z "${MYSQL_DATABASE}" ]; then
        NOTICE ''
        NOTICE "Creating user database ${MYSQL_USER} ..."
        echo "
        CREATE DATABASE IF NOT EXISTS \`${MYSQL_USER}\`;
        GRANT ALL PRIVILEGES ON \`${MYSQL_USER}\`.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
        FLUSH PRIVILEGES;
        " >> ${INIT_FILE}
    fi

    # Update start command
    MYSQL_STARTCMD="${MYSQL_STARTCMD} --init-file=${INIT_FILE}"

fi

# Make sure the backup file can be excuted
chmod +x /etc/service.d/mariadb/bin/backup

# Let's go and start MariaDB
NOTICE ''
NOTICE 'Starting MariaDB'
NOTICE '  mysql'
NOTICE '    '"${MYSQL_STARTCMD}"
NOTICE '    --user=mysql'
NOTICE '    --pid-file=/var/run/mysqld/mysqld.pid'
if [ -n "$MYSQL_STARTPARAMS" ] ; then NOTICE '    '"$MYSQL_STARTPARAMS"; fi
NOTICE ''
exec su-exec mysql ${MYSQL_STARTCMD} --user=mysql --pid-file=/var/run/mysqld/mysqld.pid ${MYSQL_STARTPARAMS}

# This exit code will be sent as the first parameter to the finish script
exit 1
