#!/usr/bin/env bash

# shellcheck disable=SC2086

# Run only when mariadb service is started.
if [ -f "/etc/service/mariadb/supervise/lock" ]; then
    # No backup if the root password is not defined
    [ -z ${MYSQL_ROOT_PASSWORD} ] && exit

    # Get the list of databases to backup
    DATABASES=$(mysql --user=root --password=${MYSQL_ROOT_PASSWORD} -e 'show databases;' | sed 1d | grep -v -E "(mysql|information_schema|performance_schema)")
    # Define the backup directory
    MYSQL_BACKUP_DIR=${MYSQL_BACKUP_DIR:="/mariadb/backup"}
    # Define the number of backup to keep
    RETENTION_DAYS=${MYSQL_BACKUP_COUNT:=14}
    # date format
    DATE=$(date +"%Y%m%d%H%M")

    # Exit if there is no databases to backup
    [ -z ${DATABASES} ] && exit

    # Create backup folder if necessary
    if [ ! -d ${MYSQL_BACKUP_DIR} ]; then
        mkdir -p ${MYSQL_BACKUP_DIR}
    fi
    chmod 740 ${MYSQL_BACKUP_DIR}

    # Dump the databases in seperate names and gzip the .sql file
    for DATABASE in ${DATABASES}; do
        mysqldump --force --opt --user=root --password=${MYSQL_ROOT_PASSWORD} ${DATABASE} | gzip > "${MYSQL_BACKUP_DIR}/${DATABASE}_$DATE.sql.gz"
        chmod 640 "${MYSQL_BACKUP_DIR}/${DATABASE}_$DATE.sql.gz"
    done

    # Remove old files
    find "${MYSQL_BACKUP_DIR}/*" -type f -mtime "+${RETENTION_DAYS}" -name '*.gz' -delete
fi
