#!/bin/sh

# set -e : Exit the script if any statement returns a non-true return value.
# set -o pipefail : Check the exit code of pipeline's last command.
# set -u : Exit the script when using uninitialised variable.
set -euo pipefail

# Reset PATH to avoid messed up duplication
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Define default variables to be used in the config file
export DEFAULT_CHARACTER_SET=${DEFAULT_CHARACTER_SET:='utf8'}
export CHARACTER_SET_SERVER=${CHARACTER_SET_SERVER:='utf8'}
export COLLATION_SERVER=${COLLATION_SERVER:='utf8_general_ci'}
export TIME_ZONE=${TIME_ZONE:='+00:00'}
export KEY_BUFFER_SIZE=${KEY_BUFFER_SIZE:='16M'}
export MAX_ALLOWED_PACKET=${MAX_ALLOWED_PACKET:='1M'}
export TABLE_OPEN_CACHE=${TABLE_OPEN_CACHE:='64'}
export SORT_BUFFER_SIZE=${SORT_BUFFER_SIZE:='512K'}
export NET_BUFFER_SIZE=${NET_BUFFER_SIZE:='8K'}
export READ_BUFFER_SIZE=${READ_BUFFER_SIZE:='256K'}
export READ_RND_BUFFER_SIZE=${READ_RND_BUFFER_SIZE:='512K'}
export MYISAM_SORT_BUFFER_SIZE=${MYISAM_SORT_BUFFER_SIZE:='8M'}
export BIND_ADRESS=${BIND_ADRESS:='0.0.0.0'}
export LOG_BIN=${LOG_BIN:='mysql-bin'}
export BINLOG_FORMAT=${BINLOG_FORMAT:='mixed'}
export SERVER_ID=${SERVER_ID:='1'}
export INNODB_DATA_FILE_PATH=${INNODB_DATA_FILE_PATH:='ibdata1:10M:autoextend'}
export INNODB_BUFFER_POOL_SIZE=${INNODB_BUFFER_POOL_SIZE:='16M'}
export INNODB_LOG_FILE_SIZE=${INNODB_LOG_FILE_SIZE:='5M'}
export INNODB_LOG_BUFFER_SIZE=${INNODB_LOG_BUFFER_SIZE:='8M'}
export INNODB_FLUSH_LOG_AT_TRX_COMMIT=${INNODB_FLUSH_LOG_AT_TRX_COMMIT:='1'}
export INNODB_LOCK_WAIT_TIMEOUT=${INNODB_LOCK_WAIT_TIMEOUT:='50'}
export INNODB_USE_NATIVE_AIO=${INNODB_USE_NATIVE_AIO:='1'}
export INNODB_FILE_PER_TABLE=${INNODB_FILE_PER_TABLE:='ON'}
export MAX_ALLOWED_PACKET=${MAX_ALLOWED_PACKET:='16M'}
export KEY_BUFFER_SIZE=${KEY_BUFFER_SIZE:='20M'}
export SORT_BUFFER_SIZE=${SORT_BUFFER_SIZE:='20M'}
export READ_BUFFER=${READ_BUFFER:='2M'}
export WRITE_BUFFER=${WRITE_BUFFER:='2M'}

# Create conf.d directory
mkdir -p "/etc/mysql/conf.d/"
chown -R mysql:mysql "/etc/mysql/conf.d/"

# Use templater to generate my.cnf
templater /etc/service.d/mariadb/cnf/my.cnf.tpl > /etc/mysql/my.cnf
